import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import Progressbar from "@/components/NextProgressbar";
import Nav from "@/components/navigation/nav";
import { ThemeProvider } from "@/components/theme-provider";
import Toaster from "@/components/ui/toaster";
import "./globals.css";

const geist = GeistSans;

export const metadata: Metadata = {
  title: {
    template: "%s | Sprout & Scribble",
    default: "Sprout & Scribble", // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geist.className} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto max-w-7xl flex-grow px-6 md:px-12">
            <Nav />
            <Progressbar />
            <Toaster />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
